server:
  port:  ${PORT:8080}

spring:
  profiles:
    active:
    - ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoint: 
    beans:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true